version: '3.3'

services:
  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass foo
    ports:
      - '6379:6379'
    networks:
      default:
        aliases:
          - redis-server

  gowitness:
    build: ./gowitness
    working_dir: /dist
    command: ./main
    restart: always
    hostname: gowitness0001
    expose: 
      - 8080
    environment:
      - POSTGRES_HOST=globalwitness.cw9ykmpsqcdj.us-east-2.rds.amazonaws.com
      - POSTGRES_PASS=CIGjGP49TtmP7ngN9nRiFQjdXXFpD1UQ
      - POSTGRES_DB=globalwitness
      - POSTGRES_USER=postgres
      - MAX_PEERS=32
      - REDIS_URL=redis-server:6379
      - REDIS_PASS=foo
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      default:
        aliases:
          - edge1
    depends_on:
      - redis
