version: '3.3'

volumes:
  pgdata: {}

services:
  psql:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - psqlserver
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data

  gowitness:
    build: ./gowitness
    working_dir: /dist
    command: ./main
    restart: always
    hostname: gowitness0001
    expose: 
      - 8080
    environment:
      - POSTGRES_HOST=globalwitness.cxl4vro2ssou.us-east-1.rds.amazonaws.com
      - MAX_PEERS=1024
      - POSTGRES_PASS=yvpd7zt82kMk1g3Co92PVKRGjHF2FYEUi0rtr
      - POSTGRES_USER=globalwitness
      - POSTGRES_DB=globalwitness
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      default:
        aliases:
          - edge1
    depends_on:
      - psql
